export const JOB_LOAD_REQUEST = 'JOB_LOAD_REQUEST';
export const JOB_LOAD_SUCCESS = 'JOB_LOAD_SUCCESS';
export const JOB_LOAD_FAILED = 'JOB_LOAD_FAILED';
export const JOB_LOAD_RESET = 'JOB_LOAD_RESET';

export const SINGLE_JOB_LOAD_REQUEST = 'SINGLE_JOB_LOAD_REQUEST';
export const SINGLE_JOB_LOAD_SUCCESS = 'SINGLE_JOB_LOAD_SUCCESS';
export const SINGLE_JOB_LOAD_FAILED = 'SINGLE_JOB_LOAD_FAILED';
export const SINGLE_JOB_LOAD_RESET = 'SINGLE_JOB_LOAD_RESET';
